apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=
            - --git-user=macintoshprime
            - --git-email=@users.noreply.github.com
            - --git-url=git@github.com:cartyc/hello-k8s-deployment.git
            - --git-readonly
            - --registry-disable-scanning
